### ISSUE TITLE
feature request: specify colors for boxes

### ISSUE THREAD

**Issue by ginolhac** [koncina/iosp#1]
instead of having to choose between pre-defined blue, red, green etc... would be great to set-up ourself and you convert during post-processing

**Comment by koncina** [comment]
Since commit [ee158e3](https://github.com/koncina/iosp/commit/ee158e341762bf57536fed1a61e7206bcd062778) it is possible to define your own box colours (a request similar to the one in issue #9). Have a look at the example [here](https://koncina.github.io/iosp/box_colours.html) explaining how to define your own colours. You should at least provide a name (with a `bg-` prefix which is otherwise automatically added) and a background colour. You can also override the background colours of the header, the text and the header text.
