### ISSUE TITLE
Text with hyperlink not interpreted properly

### ISSUE THREAD

**Issue by tungttnguyen** [koncina/iosp#15]
I've just seen this error in both `master` and `dev` versions. Normal RMarkdown doc didn't have this issue

- Code:

### Box with title {.box-6 .bg-blue}
A box can have a title
%end%
<div class = "small"; style='text-align:right;'>[This is a link](https://github.com/koncina/iosp)</div>   

- Result:
   + dev
![iosp_dev_link_error](https://user-images.githubusercontent.com/6590141/32233575-eafb5834-be17-11e7-9c39-b2cba83b92d0.png)

   + master
![iosp_master_link_error](https://user-images.githubusercontent.com/6590141/32233582-efe27346-be17-11e7-8e29-f9836bec2e7c.png)

Any thought on what went wrong? 

Thanks!

**Comment by koncina** [comment]
Thank for your feedback.
Unfortunately, I'm not able to reproduce this bug yet. I tried your code with the actual `dev` version and you can have a look at the result [here](https://koncina.github.io/iosp/issue_015.html#2).
Could you confirm that the [associated source code](https://raw.githubusercontent.com/koncina/iosp/gh-pages/issue_015.Rmd) does not render properly in your hands?

Are all hyperlinks misinterpreted or only those following the `%end%` keyword?

For now I would suspect a platform or version dependent incompatibility issue but I will have to figure out what is exactly going on.
If the problem is confirmed with [this source code](https://raw.githubusercontent.com/koncina/iosp/gh-pages/issue_015.Rmd), could you provide me some informations:
- your platform (although we tested IOSP on Linux, Windows and MAC OS).
- your rmarkdown version
- your pandoc version (are you using the pandoc shipped with rstudio?)

**Comment by tungttnguyen** [comment]
Thanks! Your file works fine on my laptop now. But when I put `style='text-align:right'` to format the link to the right, it still didn't work. Any idea how to fix it?    

**Edit**: nvm, `<div class = "small"; style='text-align:right'>[This is a link](https://github.com/koncina/iosp)</div> ` should have been `<div class = "small" style='text-align:right'>[This is a link](https://github.com/koncina/iosp)</div> `

	---
	title: "Issue 015"
	author: "Eric Koncina"
	date: "`r Sys.Date()`"
	output:
	  iosp::ioslides_plus:
		self_contained: no
		footer: "Created with [ioslides plus](https://github.com/koncina/iosp)"
	---

	##

	### Box with title {.box-6 .bg-blue}

	A box can have a title

	%end%

	[This is a link](https://github.com/koncina/iosp)

	<div class = "small"; style='text-align:right'>[This is a link](https://github.com/koncina/iosp)</div>

**Comment by koncina** [comment]
You pointed out a regression when using  `text-align:right` with the actual development version. Your code is still working with the current [master branch](https://github.com/koncina/iosp/commit/2cea3c7f8fc49f078a9616d61e57499c479575ff) but as I'm now using CSS flexboxes you need to set a width to your `div` container.

You can either just add the `col-12` class to your `div` container or, if you are reusing such an alignment, you could define a new css class in combination with the column IOSP shortcut.

~~~
##

#### 1. Won't work:

<div class = "small" style='text-align:right'>[This is a link](https://github.com/koncina/iosp)</div> 

It's even messing up the text surrounding the `div` tag...

#### 2. Works:

<div class = "small col-12" style='text-align:right'>[This is a link](https://github.com/koncina/iosp)</div>

#### 3. Using IOSP shortcuts:

```{css, echo = FALSE}
.align-right {
  text-align:right;
}
```

### {.col-12 .small .align-right}

[This is a link](https://github.com/koncina/iosp)
~~~

which renders like this:

![image](https://user-images.githubusercontent.com/6618930/32773768-89d65b26-c92a-11e7-8154-cba7c5bac147.png)

Options 2 and 3 exhibit small alignment differences as in option 3, pandoc embeds the link in a paragraph.
