### ISSUE TITLE
Can we add circle or arrow to slides?

### ISSUE THREAD

**Issue by tungttnguyen** [koncina/iosp#16]
Hello,

I was wondering if we can do something like this with `iosp`   

![iosp](https://user-images.githubusercontent.com/6590141/34319812-d486d0b8-e79f-11e7-9eab-e7d3dba1efd3.png)

Thanks!   

-- Tung

**Comment by koncina** [comment]
Hello,

With the actual version, it is unfortunately not possible to draw circles around slide elements as shown in your picture. 

However, using the [latest commit](https://github.com/koncina/iosp/commit/35de517a00b683b15a8bf1d216b2fc1bdfef2d13) you could try a workaround in order to highlight individual elements.

Have a look at the following [source Rmd](https://raw.githubusercontent.com/koncina/iosp/gh-pages/issue_016.Rmd) and/or [rendered output](https://koncina.github.io/iosp/issue_016.html): I’m using a css double class selector to setup a yellow/red shadow (which will highlight the element) and a gray shadow (to fade out the remaining elements).

Just assign the box to be emphasized to the classes `to-build` and `highlight` (or `highlight2` in the second example). The trick relies on the fact that the IOSlides javascript code will remove the `to-build` class after pressing a key (and will transiently assign the `build-current` class). In the file you can find two different methods: a transient one (using  `build-current`) and a lasting one (to style everything that is still `highlight` but not `to-build` anymore).

Of course this is not ideal and only a limited workaround.

**Comment by tungttnguyen** [comment]
Thanks for the detailed response! Would be nice to have the circle but this workaround will do it for now
